### ISSUE TITLE
Prints nSiTU $USERNAME

### ISSUE THREAD

**Issue by computersarecool** [randymorris/tramp-term.el#6]
When using tramp term and performing shell commands I constantly see
`nSiTu ` followed by my username.

For instance:
```
username@raspberry/usr/bin/tightvncserver -kill :2                                                                                                                                      
Killing Xtightvnc process ID 17565                                                                                                                                                             
nSiTu username                                                                                                                                                                                  
username@raspberrypi~ ()$       
```
It's possible this is on my end but I don't see this when I use SSH and Emacs from ANSI-term

**Comment by randymorris** [comment]
I've seen this in the past as well with both tramp-term and just the snippets from the emacs wiki that tramp-term is based on.  That string is part of the escape sequences that are used under the hood to set the username/host/directory variables that are then used to generate a tramp compatible filename.  It seems that sometimes ansi-term doesn't fully interpret the escape sequences sometimes (the full escape sequence there is "AnSiTu", not just "nSiTu").  The reason you see it after every command is because these escape sequences are printed before the prompt is drawn by taking over bash's `PROMPT_COMMAND`.

I haven't been able to reproduce this consistently, but I would imagine the issue would be somewhere in ansi-term rather than tramp-term.  The code that prints these escape sequences is [pretty straightforward](https://github.com/randymorris/tramp-term.el/blob/983ed67ee65d26a51c641f306fa6b921ec83eeaf/tramp-term.el#L113-L124), not much we can do differently on this side.

**Comment by computersarecool** [comment]
Makes sense to me.
